<?
class utilMimeType
{
	const DEFAULTS		= 'application/octet-stream';
	
	public static $mimetypes = array (
			'xml' => 'application/xml', 'xcml' => 'application/xml', 
			'xht' => 'application/xhtml+xml', 'xhtml' => 'application/xhtml+xml', 
			'css' => 'text/css', 
			'js' => 'application/x-javascript', 
			'html' => 'text/html', 'vhtml' => 'text/html', 'dtml' => 'text/html', 'htm' => 'text/html', 
			
			'png' => 'image/png', 
			'jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg', 'jpe' => 'image/jpeg', 
			'gif' => 'image/gif', 
			'bmp' => 'image/bmp', 
			'ico' => 'image/x-icon', 
			
			'dtd' => 'application/xml-dtd', 
			'xsl' => 'application/xml', 
			'xslt' => 'application/xslt+xml', 
			'xul' => 'application/vnd.mozilla.xul+xml', 
			'wml' => 'text/vnd.wap.wml', 
			
			'txt' => 'text/plain', 'asc' => 'text/plain', 
			'rtf' => 'text/rtf', 
			'doc' => 'application/msword', 'docx' => 'application/msword', 
			'xls' => 'application/vnd.ms-excel', 
			'ppt' => 'application/vnd.ms-powerpoint', 
			'pdf' => 'application/pdf', 
			
			'zip' => 'application/zip', 	//'application/x-zip-compressed'
			'rar' => 'application/rar', 
			'gz' => 'application/x-gzip', 
			
			'swf' => 'application/x-shockwave-flash', 
			'flv' => 'video/x-flv', 
			'wav' => 'audio/x-wav', 
			'mp3' => 'audio/mpeg', 		//'audio/mpeg3'
			
			'apk' => 'application/vnd.android.package-archive',
			
			'3gp' => 'video/3gpp', 
			'ai' => 'application/postscript', 
			'aif' => 'audio/x-aiff', 'aifc' => 'audio/x-aiff', 'aiff' => 'audio/x-aiff', 
			'atom' => 'application/atom+xml', 
			'au' => 'audio/basic', 
			'avi' => 'video/x-msvideo', 
			'bcpio' => 'application/x-bcpio', 
			//'bin' => 'application/octet-stream', 
			'cdf' => 'application/x-netcdf', 
			'cgm' => 'image/cgm', 
			//'class' => 'application/octet-stream', 
			'cpio' => 'application/x-cpio', 
			'cpt' => 'application/mac-compactpro', 
			'csh' => 'application/x-csh', 
			'dcr' => 'application/x-director', 'dir' => 'application/x-director', 
			'dif' => 'video/x-dv', 
			'djv' => 'image/vnd.djvu', 'djvu' => 'image/vnd.djvu', 
			//'dll' => 'application/octet-stream', 
			//'dmg' => 'application/octet-stream', 'dms' => 'application/octet-stream', 
			'dv' => 'video/x-dv', 
			'dvi' => 'application/x-dvi', 
			'dxr' => 'application/x-director', 
			'eps' => 'application/postscript', 
			'etx' => 'text/x-setext', 
			//'exe' => 'application/octet-stream', 
			'ez' => 'application/andrew-inset', 
			'gram' => 'application/srgs', 
			'grxml' => 'application/srgs+xml', 
			'gtar' => 'application/x-gtar', 
			'hdf' => 'application/x-hdf', 
			'hqx' => 'application/mac-binhex40',
			'ice' => 'x-conference/x-cooltalk', 
			'ics' => 'text/calendar', 
			'ief' => 'image/ief', 
			'ifb' => 'text/calendar', 
			'iges' => 'model/iges', 
			'igs' => 'model/iges', 
			'jnlp' => 'application/x-java-jnlp-file', 
			'jp2' => 'image/jp2', 
			'kar' => 'audio/midi', 
			'latex' => 'application/x-latex', 
			//'lha' => 'application/octet-stream', 'lzh' => 'application/octet-stream', 
			'm3u' => 'audio/x-mpegurl', 
			'm4a' => 'audio/mp4a-latm', 'm4p' => 'audio/mp4a-latm', 
			'm4u' => 'video/vnd.mpegurl', 
			'm4v' => 'video/x-m4v', 
			'mac' => 'image/x-macpaint', 
			'man' => 'application/x-troff-man', 
			'mathml' => 'application/mathml+xml', 
			'me' => 'application/x-troff-me', 
			'mesh' => 'model/mesh', 
			'mid' => 'audio/midi', 'midi' => 'audio/midi', 
			'mif' => 'application/vnd.mif', 
			'mov' => 'video/quicktime', 
			'movie' => 'video/x-sgi-movie', 
			'mp4' => 'video/mp4', 
			'mp2' => 'audio/mpeg', 'mpe' => 'video/mpeg', 'mpeg' => 'video/mpeg', 'mpg' => 'video/mpeg', 'mpga' => 'audio/mpeg', 
			'ms' => 'application/x-troff-ms', 
			'msh' => 'model/mesh', 
			'mxu' => 'video/vnd.mpegurl', 
			'nc' => 'application/x-netcdf', 
			'oda' => 'application/oda', 
			'ogg' => 'application/ogg', 
			'ogv' => 'video/ogv', 
			'pbm' => 'image/x-portable-bitmap', 
			'pct' => 'image/pict', 
			'pdb' => 'chemical/x-pdb', 
			'pgm' => 'image/x-portable-graymap', 
			'pgn' => 'application/x-chess-pgn', 
			'pic' => 'image/pict', 'pict' => 'image/pict', 
			'pnm' => 'image/x-portable-anymap', 'ppm' => 'image/x-portable-pixmap', 
			'pnt' => 'image/x-macpaint', 'pntg' => 'image/x-macpaint', 
			'ps' => 'application/postscript', 
			'qt' => 'video/quicktime', 'qti' => 'image/x-quicktime', 'qtif' => 'image/x-quicktime', 
			'ra' => 'audio/x-pn-realaudio', 'ram' => 'audio/x-pn-realaudio', 
			'ras' => 'image/x-cmu-raster', 
			'rdf' => 'application/rdf+xml', 
			'rgb' => 'image/x-rgb', 
			'rm' => 'application/vnd.rn-realmedia', 
			'roff' => 'application/x-troff', 
			'rtx' => 'text/richtext', 
			'sgm' => 'text/sgml', 'sgml' => 'text/sgml', 
			'sh' => 'application/x-sh', 
			'shar' => 'application/x-shar', 
			'silo' => 'model/mesh', 
			'sit' => 'application/x-stuffit', 
			'skd' => 'application/x-koan', 'skm' => 'application/x-koan', 'skp' => 'application/x-koan', 'skt' => 'application/x-koan', 
			'smi' => 'application/smil', 'smil' => 'application/smil', 
			'snd' => 'audio/basic', 
			'so' => 'application/octet-stream', 
			'spl' => 'application/x-futuresplash', 
			'src' => 'application/x-wais-source', 
			'sv4cpio' => 'application/x-sv4cpio', 
			'sv4crc' => 'application/x-sv4crc', 
			'svg' => 'image/svg+xml', 
			't' => 'application/x-troff', 
			'tar' => 'application/x-tar', 
			'tcl' => 'application/x-tcl', 
			'tex' => 'application/x-tex', 
			'texi' => 'application/x-texinfo', 
			'texinfo' => 'application/x-texinfo', 
			'tif' => 'image/tiff', 'tiff' => 'image/tiff', 
			'tr' => 'application/x-troff', 
			'tsv' => 'text/tab-separated-values', 
			'ustar' => 'application/x-ustar', 
			'vcd' => 'application/x-cdlink', 
			'vrml' => 'model/vrml', 
			'vxml' => 'application/voicexml+xml', 
			'wbmp' => 'image/vnd.wap.wbmp', 
			'wbxml' => 'application/vnd.wap.wbxml', 
			'webm' => 'video/webm', 
			'wmlc' => 'application/vnd.wap.wmlc', 
			'wmls' => 'text/vnd.wap.wmlscript', 
			'wmlsc' => 'application/vnd.wap.wmlscriptc', 
			'wmv' => 'video/x-ms-wmv', 
			'wrl' => 'model/vrml', 
			'xbm' => 'image/x-xbitmap', 'xpm' => 'image/x-xpixmap', 
			'xwd' => 'image/x-xwindowdump', 
			'xyz' => 'chemical/x-xyz' );
	
	public static function get($ext)
	{
		return (isset(self::$mimetypes[$ext]) ? self::$mimetypes [$ext] : self::DEFAULTS);
	}
	
}
